### ISSUE TITLE
Load error while requiring rapidomize gem

### ISSUE THREAD

**Issue by nisalb** [rapidomize/rapidomize-ruby-sdk#1]
Following error is generated when `rapidomize` gem is required.

```ruby
>> require 'rapidomize'
Traceback (most recent call last):
        5: from ./bin/console:14:in `<main>'
        4: from (irb):1:in `<main>'
        3: from (irb):1:in `require'
        2: from /home/edz/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rapidomize-1.0.0/lib/rapidomize.rb:9:in `<top (required)>'
        1: from /home/edz/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rapidomize-1.0.0/lib/rapidomize.rb:9:in `require'
LoadError (cannot load such file -- rapidomize/error/rapidomize_error)
```

**Comment by nisalb** [comment]
This was due to a misconfiguration in the gemspec file.

`spec.files` does not accept directory names. But a directory name was given and it is not included in the gem file. Hence only the `rapidomize.rb` is published in v1.0.0.

This is fixed in v1.0.1
